export const types = {
    REQUEST_ADD_PHONE_CARRIER: "REQUEST_ADD_PHONE_CARRIER",
    ADD_PHONE_CARRIER_SUCCESS: "ADD_PHONE_CARRIER_SUCCESS",
    ADD_PHONE_CARRIER_FAILURE: "ADD_PHONE_CARRIER_FAILURE",
    REQUEST_REMOVE_PHONE_CARRIER: "REQUEST_REMOVE_PHONE_CARRIER",
    REMOVE_PHONE_CARRIER_SUCCESS: "REMOVE_PHONE_CARRIER_SUCCESS",
    REMOVE_PHONE_CARRIER_FAILURE: "REMOVE_PHONE_CARRIER_FAILURE",
    REQUEST_UPDATE_PHONE_CARRIER: "REQUEST_UPDATE_PHONE_CARRIER",
    UPDATE_PHONE_CARRIER_SUCCESS: "UPDATE_PHONE_CARRIER_SUCCESS",
    UPDATE_PHONE_CARRIER_FAILURE: "UPDATE_PHONE_CARRIER_FAILURE",
    REQUEST_GET_PHONE_CARRIER: "REQUEST_GET_PHONE_CARRIER",
    GET_PHONE_CARRIER_SUCCESS: "GET_PHONE_CARRIER_SUCCESS",
    GET_PHONE_CARRIER_FAILURE: "GET_PHONE_CARRIER_FAILURE",
    REQUEST_GET_PHONE_CARRIERS: "REQUEST_GET_PHONE_CARRIERS",
    GET_PHONE_CARRIERS_SUCCESS: "GET_PHONE_CARRIERS_SUCCESS",
    GET_PHONE_CARRIERS_FAILURE: "GET_PHONE_CARRIERS_FAILURE",

}