export const REQUEST_EASY_TEST = "REQUEST_EASY_TEST";
export const EASY_TEST_SUCCESS = "EASY_TEST_SUCCESS";
export const EASY_TEST_FAILURE = "EASY_TEST_FAILURE";

export const REQUEST_API_TEST = "REQUEST_API_TEST";
export const API_TEST_SUCCESS = "API_TEST_SUCCESS";
export const API_TEST_FAILURE = "API_TEST_FAILURE";
