const types = {
    REQUEST_EASY_TEST2: "REQUEST_EASY_TEST2",
    EASY_TEST_SUCCESS2: "EASY_TEST_SUCCESS2",
    EASY_TEST_FAILURE2: "EASY_TEST_FAILURE2",
    REQUEST_API_TEST2: "REQUEST_API_TEST2",
    API_TEST_SUCCESS2: "API_TEST_SUCCESS2",
    API_TEST_FAILURE2: "API_TEST_FAILURE2"
}

export default types
