const env = {
    dbUri: process.env.DB_URI,
    dbIp: process.env.DB_IP,
    dbName: process.env.DB_NAME,
    dbProtocol: process.env.DB_PROTOCOL,
    nodeEnv: process.env.NODE_ENV,
    googleClientId: process.env.GOOGLE_CLIENT_ID,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
    accessTokenSecret: process.env.ACCESS_TOKEN_SECRET,
    accessTokenExp: process.env.ACCESS_TOKEN_EXPIRES,
    refreshTokenSecret: process.env.ACCESS_TOKEN_SECRET,
    refreshTokenExp: process.env.ACCESS_TOKEN_EXPIRES,
    emailTokenSecret: process.env.EMAIL_TOKEN_SECRET,
    emailTokenExp: process.env.EMAIL_TOKEN_EXPIRES,
    phoneTokenSecret: process.env.PHONE_TOKEN_SECRET,
    phoneTokenExp: process.env.PHONE_TOKEN_EXPIRES,
    forgotIdTokenSecret: process.env.FORGOT_ID_TOKEN_SECRET,
    forgotIdTokenExp: process.env.FORGOT_ID_TOKEN_EXPIRES,
    resetPasswordTokenSecret: process.env.RESET_PASSWORD_TOKEN_SECRET,
    resetPasswordTokenExp: process.env.RESET_PASSWORD_TOKEN_EXPIRES,
    organizationTokenSecret: process.env.ORGANIZATION_TOKEN_SECRET,
    organizationTokenExp: process.env.ORGANIZATION_TOKEN_EXPIRES,
    originTokenSecret: process.env.ORIGIN_TOKEN_SECRET,
    originTokenExp: process.env.ORIGIN_TOKEN_EXPIRES,
}