export const ADD_NEW_QUERY_DATA = "ADD_NEW_QUERY_DATA";
export const GET_EXISTING_QUERY = "GET_EXISTING_QUERY";
export const GET_ALL_QUERIES = "GET_ALL_QUERIES";
export const UPDATE_EXISTING_QUERY_DATA = "UPDATE_EXISTING_QUERY_DATA";
export const DELETE_EXISTING_QUERY_DATA = "DELETE_EXISTING_QUERY_DATA";

