export const types = {
    REQUEST_LOGOUT: "REQUEST_LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    REQUEST_LOGIN: "REQUEST_LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    REQUEST_SIGN_UP: "REQUEST_SIGN_UP",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    LOGIN_NO_PHONE_SUCCESS: "LOGIN_NO_PHONE_SUCCESS",
    REQUEST_CHECK_AUTH: "REQUEST_CHECK_AUTH",
    CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE",
    CHECK_AUTH_NOT_LOGGED_IN: "CHECK_AUTH_NOT_LOGGED_IN",
    CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS",

    REQUEST_TWO_POINT_LOGIN: "REQUEST_TWO_POINT_LOGIN",
    TWO_POINT_LOGIN_SUCCESS: "TWO_POINT_LOGIN_SUCCESS",
    TWO_POINT_LOGIN_FAILURE: "TWO_POINT_LOGIN_FAILURE",

    REQUEST_FORGOT_PASSWORD: "REQUEST_FORGOT_PASSWORD",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

    REQUEST_RESET_PASSWORD: "REQUEST_RESET_PASSWORD",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE"
}
