export const types = {
    
    REQUEST_VERIFY_EMAIL: 'REQUEST_VERIFY_EMAIL',
    VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
    VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

    REQUEST_VERIFY_PHONE: 'REQUEST_VERIFY_PHONE',
    VERIFY_PHONE_SUCCESS: 'VERIFY_PHONE_SUCCESS',
    VERIFY_PHONE_FAILURE: 'VERIFY_PHONE_FAILURE',

    REQUEST_UPDATE_EMAIL: 'REQUEST_UPDATE_EMAIL',
    UPDATE_EMAIL_SUCCESS: 'UPDATE_EMAIL_SUCCESS',
    UPDATE_EMAIL_FAILURE: 'UPDATE_EMAIL_FAILURE',

    REQUEST_UPDATE_PHONE: 'REQUEST_UPDATE_PHONE',
    UPDATE_PHONE_SUCCESS: 'UPDATE_PHONE_SUCCESS',
    UPDATE_PHONE_FAILURE: 'UPDATE_PHONE_FAILURE',

}