export const REQUEST_EASY_TEST2 = "REQUEST_EASY_TEST2";
export const EASY_TEST_SUCCESS2 = "EASY_TEST_SUCCESS2";
export const EASY_TEST_FAILURE2 = "EASY_TEST_FAILURE2";

export const REQUEST_API_TEST2 = "REQUEST_API_TEST2";
export const API_TEST_SUCCESS2 = "API_TEST_SUCCESS2";
export const API_TEST_FAILURE2 = "API_TEST_FAILURE2";
