export const types = {
    REQUEST_ADD_ORGANIZATION: "REQUEST_ADD_ORGANIZATION",
    ADD_ORGANIZATION_SUCCESS: "ADD_ORGANIZATION_SUCCESS",
    ADD_ORGANIZATION_FAILURE: "ADD_ORGANIZATION_FAILURE",
    REQUEST_GET_ORGANIZATION: "REQUEST_GET_ORGANIZATION",
    GET_ORGANIZATION_SUCCESS: "GET_ORGANIZATION_SUCCESS",
    GET_ORGANIZATION_FAILURE: "GET_ORGANIZATION_FAILURE",
    REQUEST_UPDATE_ORGANIZATION: "REQUEST_UPDATE_ORGANIZATION",
    UPDATE_ORGANIZATION_SUCCESS: "UPDATE_ORGANIZATION_SUCCESS",
    UPDATE_ORGANIZATION_FAILURE: "UPDATE_ORGANIZATION_FAILURE",
    REQUEST_REMOVE_ORGANIZATION: "REQUEST_REMOVE_ORGANIZATION",
    REMOVE_ORGANIZATION_SUCCESS: "REMOVE_ORGANIZATION_SUCCESS",
    REMOVE_ORGANIZATION_FAILURE: "REMOVE_ORGANIZATION_FAILURE",
    REQUEST_GET_ORGANIZATIONS: "REQUEST_GET_ORGANIZATIONS",
    GET_ORGANIZATIONS_SUCCESS: "GET_ORGANIZATIONS_SUCCESS",
    GET_ORGANIZATIONS_FAILURE: "GET_ORGANIZATIONS_FAILURE",
}

