export const types = {
    REQUEST_SET_USER: 'REQUEST_SET_USER',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_FAILURE: 'SET_USER_FAILURE',

    REQUEST_GET_USER: 'REQUEST_GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    REQUEST_GET_USERS: 'REQUEST_GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    REQUEST_ADD_USER: 'REQUEST_ADD_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',

    REQUEST_DELETE_USER: 'REQUEST_DELETE_USER',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    REQUEST_UPDATE_USER: 'REQUEST_UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    
}